name: second_ecommerce_app_flutter
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.3
  persistent_bottom_nav_bar_v2: ^4.2.8
  flutter_carousel_widget: ^2.1.2
  cached_network_image: ^3.3.0
  glassmorphism_ui: ^0.3.0
  readmore: ^2.2.0
  flutter_phosphor_icons: ^0.0.1+6
  equatable: ^2.0.5
  flutter_dash: ^1.0.0
  selectable_list: ^0.1.1
  font_awesome_flutter: ^10.6.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^5.0.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
