// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo0l_BthwK6xhB7-X0Y23jSmyajciU2Og',
    appId: '1:106624480964:web:fa7dfa7595b5617c09bb91',
    messagingSenderId: '106624480964',
    projectId: 'sky-ecommerce-app-36479',
    authDomain: 'sky-ecommerce-app-36479.firebaseapp.com',
    storageBucket: 'sky-ecommerce-app-36479.appspot.com',
    measurementId: 'G-EG1FXRSCCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM0u4gyHlNNXF6VTv2AsdHpqecjvPmygc',
    appId: '1:106624480964:android:f5077c63512cd87809bb91',
    messagingSenderId: '106624480964',
    projectId: 'sky-ecommerce-app-36479',
    storageBucket: 'sky-ecommerce-app-36479.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0rHDbFRwSW8LIaZF7dw5hM8RLN4aK_d8',
    appId: '1:106624480964:ios:4c41ffa75340406e09bb91',
    messagingSenderId: '106624480964',
    projectId: 'sky-ecommerce-app-36479',
    storageBucket: 'sky-ecommerce-app-36479.appspot.com',
    iosBundleId: 'com.example.secondEcommerceAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0rHDbFRwSW8LIaZF7dw5hM8RLN4aK_d8',
    appId: '1:106624480964:ios:2e8eb113d872504309bb91',
    messagingSenderId: '106624480964',
    projectId: 'sky-ecommerce-app-36479',
    storageBucket: 'sky-ecommerce-app-36479.appspot.com',
    iosBundleId: 'com.example.secondEcommerceAppFlutter.RunnerTests',
  );
}
